git:
  commitMessage: 'chore: release v${version}'

github:
  release: true
  releaseName: 'v${version}'
  tokenRef: 'GITHUB_TOKEN'

npm:
  publish: false

plugins:
  '@release-it/keep-a-changelog':
    filename: 'CHANGELOG.md'
